{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'auto_install': True,
    'conflicts': [],
    'css': [],
    'data': ['views/fields_form.xml', 'views/models_form.xml'],
    'demo': [],
    'demo_xml': [],
    'depends': ['base'],
    'external_dependencies': {'bin': [], 'python': ['names', 'arrow']},
    'installable': True,
    'js': [],
    'name': 'anonymize',
    'qweb': [],
    'test': [],
    'version': '13.0.1.1'}
